[package]
name = "calculator-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.5.0", features = ["server", "transport-io"] }
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["rt-multi-thread"] }

[dev-dependencies]
slab = "0.4.11"